x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

name: tigilabs

services:
  postgres:
    image: postgres:16-alpine
    logging: *default-logging
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
      POSTGRES_DB: tigilabs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
