name: tigilabs

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  tigilabs-api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    expose:
      - "3101"
    networks:
      - default
      - db

  tigilabs-web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    restart: unless-stopped
    logging: *default-logging
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
    expose:
      - "3100"
    depends_on:
      tigilabs-api:
        condition: service_started
    networks:
      - default
      - nginx

networks:
  db:
    external: true
    name: db
  nginx:
    external: true
    name: ${NGINX_NETWORK:-proxy}
